server:
  port: 20002
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hunter?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: ch-consumer-whichrel
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry